#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>

#import <CoreData/CoreData.h>
#import <CoreBluetooth/CoreBluetooth.h>
#import <CoreLocation/CoreLocation.h>

//#import <zlib.h>

// reduce the compiling error that's autogenerated from -swift.h file
//#import <MessageUI/MessageUI.h>
#import <MapstedCore/MapstedCore-Swift.h>
#import <MapstedMap/MapstedMap-Swift.h>
//#import <MapstedMapUi/MapstedMapUi-Swift.h>
//#import <MapstedTriggersCore/MapstedTriggersCore-Swift.h>
//
#import "AwesomeProject-Swift.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"AwesomeProject";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// this method will be called from the RCTBridge
- (void) goToMapView {
  NSLog(@"RN binding - Native View");
  dispatch_async(dispatch_get_main_queue(), ^{
    // Do this instead
    MapViewController *vc = [MapViewController new];
    [self.window.rootViewController presentViewController:vc animated:true completion:NULL];
  });
}

- (void)goToReactNative {

  [self.window.rootViewController dismissViewControllerAnimated:TRUE completion:nil];

}

@end
