require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# platform :ios, min_ios_version_supported
platform :ios, '13.0'

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AwesomeProject' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  # Mapsted map start
  # platform :ios, '13.0'

  source 'https://github.com/CocoaPods/Specs.git'
  # Real machine
  #source 'https://github.com/Mapsted/podspec.git'
  # Simulator
  source 'https://github.com/Mapsted/podspec-simulator.git'
  # Resolve react_native_pods.rb with node to allow for hoisting
  use_frameworks!
  # use_frameworks! :linkage => :static
  # If you only need positioning, include this pod only!
  pod 'mapsted-sdk-core', '~> 5.3.0', :modular_headers => true

  # If you are displaying maps, include the following two pods
  pod 'mapsted-sdk-core-map', :modular_headers => true
  pod 'mapsted-sdk-map', '~> 5.3.0', :modular_headers => true

  # If you want prebuilt map-ui (e.g., routing UI), include this pod
  pod 'mapsted-sdk-map-ui', '~> 5.3.0', :modular_headers => true

  # If you want prebuilt Mapsted UI/UX, include this pod
  # pod 'mapsted-sdk-ui-components', '~> 5.1.3'

  # If you want to incorporate the Mapsted Location Marketing SDK, include this pod
  # pod 'mapsted-sdk-loc-marketing', '~> 5.1.3'

  # If you want to incorporate the Mapsted Alerts SDK, include this pod
  # pod 'mapsted-sdk-alerts', '~> 5.1.3'
  ## Mapsted map end
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AwesomeProjectTests' do
    inherit! :complete
    # Pods for testing
  end
  

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
#    installer.pods_project.targets.each do |target|
#        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
#          target.build_configurations.each do |config|
#              config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
#          end
#        end
#    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
